Feature/ahc 1014 local dev
bchd/bahc-ohana-ui pull request #1
Opened 2019-02-25 17:49 UTC by mkantzerFearless

docker-local environment for UI

2019-03-05 14:35 UTC, solipet requested changes

2019-03-05 14:35 UTC, solipet commented on config/environments/docker-local.rb
> +    config.log_formatter = ::Logger::Formatter.new
Since this is the only section that differs from `development`, should get rid of everything above and replace with:
```
# Same settings as development
require Rails.root.join('config', 'environments', 'development')
```

2019-03-29 13:24 UTC, solipet approved these changes

2019-03-29 13:24 UTC, solipet commented on start-rails.sh
> +rails server -b 0.0.0.0 -p 3000
you probably still want to run this as `bundle exec rails ...`

2019-03-29 13:26 UTC, mkantzerFearless commented
Don't Need

2019-03-29 13:26 UTC, closed without merging