Zube 189 service categories menu and 200 remove left menu search from location details
bchd/bahc-ohana-ui pull request #120
Opened 2021-01-13 02:11 UTC by anna-dorigo

Ticket intended to provide functionality for the following tickets: 

https://zube.io/smartlogic/bchd/c/189
https://zube.io/smartlogic/bchd/c/200

Zube - 189
Provide a drop down menu with all the categories available and an expandable div with all the subcategories listed as filter options: 

![image](https://user-images.githubusercontent.com/1304609/104397244-64961480-551a-11eb-855c-06a69b15043e.png)

![Screen Shot 2021-01-12 at 9 09 15 PM](https://user-images.githubusercontent.com/1304609/104397291-8394a680-551a-11eb-80fe-b71427929380.png)

Zube - 200
Remove left search menu from locations details view
![Screen Shot 2021-01-12 at 9 11 16 PM](https://user-images.githubusercontent.com/1304609/104397406-bf2f7080-551a-11eb-986f-60766cfb244c.png)

2021-01-13 17:43 UTC, justuseapen approved these changes

2021-01-13 17:43 UTC, justuseapen requested changes
just the one typo. otherwise i think this is fine.

2021-01-14 16:30 UTC, anna-dorigo commented on app/controllers/locations_controller.rb
> +    permited = params.permit(:category_id)
👍🏽

2021-01-19 18:48 UTC, justuseapen approved these changes

2021-01-19 21:05 UTC, merged