140 - adding unique meta description tags to each page
bchd/bahc-ohana-ui pull request #169
Opened 2021-12-10 15:31 UTC by stonefilipczak

2021-12-13 17:48 UTC, oestrich requested changes

2021-12-13 17:48 UTC, oestrich commented on app/views/shared/_head.html.haml
> +%meta{ content: yield(:meta_description), name: 'description' }
Instead of this, can we do something that provides a default? Then we can remove the two that are using the default and also make sure we don't miss any pages (the login page is missing it and probably a few others)

```suggestion
<% if content_for?(:meta_description) %>
%meta{ content: yield(:meta_description), name: 'description' }
<% else %>
%meta{ content: t('meta.description', location: t('branding.location')), name: 'description' }
<% end %>
```

2021-12-13 19:10 UTC, stonefilipczak commented on app/views/shared/_head.html.haml
> +%meta{ content: yield(:meta_description), name: 'description' }
Good suggestion, I implemented that conditional and removed the default tag from the views. nice and DRY

2021-12-14 15:59 UTC, oestrich approved these changes

2021-12-14 16:00 UTC, merged