277
bchd/bahc-ohana-ui pull request #173
Opened 2021-12-27 17:06 UTC by stonefilipczak

Add optional label to holiday schedules

2022-01-11 18:09 UTC, oestrich requested changes

2022-01-11 18:09 UTC, oestrich commented on app/helpers/schedules_helper.rb
> +    unless label.nil?
I think we want to return an empty string to be able to concatenate as used above.

2022-02-01 18:54 UTC, stonefilipczak commented
Hey everybody, I had to rebase this with develop to get the new UI design, that's what all the extra commits are. The only real changes are adding the empty string return like Eric requested and changing some markup to make it work with the new UI.

2022-02-04 16:17 UTC, oestrich approved these changes

2022-02-04 16:46 UTC, merged