zube ticket #120: finds and fixes more bug for locations
bchd/bahc-ohana-ui pull request #88
Opened 2020-07-02 10:16 UTC by TheCraftedGem

2020-07-06 13:43 UTC, justuseapen requested changes

2020-07-06 13:43 UTC, justuseapen commented on app/assets/stylesheets/_base.scss
> +       // FOUND THE NEEDLE IN THE HAY STACK! For whatever reason
please remove this comment

2020-07-07 15:44 UTC, TheCraftedGem commented on app/assets/stylesheets/_base.scss
> +       // FOUND THE NEEDLE IN THE HAY STACK! For whatever reason
Removed

2020-07-08 14:10 UTC, justuseapen approved these changes

2020-07-08 14:10 UTC, merged